import { cpSync, rmSync, mkdirSync, existsSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const dist = join(root, "dist");
const docsCSS = join(root, "docs", "public", "css");

// Remove empty index.js generated by Vite
const indexJs = join(dist, "index.js");
if (existsSync(indexJs)) {
  rmSync(indexJs);
  console.log("✓ Removed dist/index.js");
}

// Generate TypeScript declaration for CSS module
const dts = `declare module "@dufeut/uizy" {
  const styles: string;
  export default styles;
}
`;
// writeFileSync(join(dist, "index.d.ts"), dts);
//console.log("✓ Generated dist/index.d.ts");

// Copy CSS to docs
mkdirSync(docsCSS, { recursive: true });
cpSync(join(dist, "index.css"), join(docsCSS, "index.css"));
console.log("✓ Copied dist/index.css to docs/public/css/");
